name: chainercv
channels:
- !!python/unicode
  'menpo'
- !!python/unicode
  'defaults'
dependencies:
  - Cython
  - opencv3=3.2.0
  - matplotlib
  - numpy
  - Pillow
  - pip:
    - "--editable=git+https://github.com/pdollar/coco.git#egg=pycocotools&subdirectory=PythonAPI"
